repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: local
    hooks:
      - id: password-detector
        name: Password Pattern Detector
        description: Detects passwords that are exactly 14 chars, start with P/p, and contain required character types
        entry: python scripts/password_detector.py
        language: system
        files: \.(py|js|ts|json|yaml|yml|txt|md|sh|env|config|conf|ini|properties)$
        pass_filenames: true
        verbose: true
